name: islam_flutter
description: "A comprehensive Flutter package for Islamic applications."
version: 0.0.2
repository: https://github.com/bqubique/islam_flutter

topics:
  - islam
  - religion

environment:
  sdk: ^3.7.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  http: ^1.6.0
  crypto: ^3.0.7
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
